/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115666-g8754c9bd82-20240611"
#endif /* AVUTIL_FFVERSION_H */
